### ISSUE TITLE
KeyError: 'strings'

### ISSUE THREAD

**Issue by lilmoomoo** [nemec/snapchat-map-scraper#6]
hi there i cant get it to work i get this every time. can you help my in any way ??
/snapchat-map-scraper$ python3 story_downloader.py scrape snap.db --randomize
Traceback (most recent call last):
  File "/home/moomoo/Desktop/kali /snapchat-map-scraper/story_downloader.py", line 397, in <module>
    scrape_locations(args.database, args.randomize, args.repeat, args.sleep, args.label)
  File "/home/moomoo/Desktop/kali /snapchat-map-scraper/story_downloader.py", line 252, in scrape_locations
    new = scrape_location(db_file, loc[0], loc[1], loc[2], loc[3], randomize, epoch)
  File "/home/moomoo/Desktop/kali /snapchat-map-scraper/story_downloader.py", line 186, in scrape_location
    titles = info['title']['strings']
KeyError: 'strings'

**Comment by nemec** [comment]
Hello @lilmoomoo, thank you for the heads up! I've just pushed a change that should fix this. Snapchat made some changes to the data on their end.

**Comment by lilmoomoo** [comment]
your fix works awesome thanks a lot
